export type CaseStudy = {
  slug: string; title: string; focus: string; description: string;
  role: string; platform: string; technologies: string[];
  overview: string[]; contributions: string[]; outcome: string;
  links: { label: string; href: string }[];
};
export const caseStudies: CaseStudy[] = [
  { slug: "plural-health", title: "Frontend engineering for Plural Health", focus: "Healthcare software · EHR · Pharmacy operations", description: "How I helped build role-based healthcare workflows and offline-ready pharmacy tools for Plural Health with Next.js, TypeScript, and React Native.", role: "Frontend Engineer", platform: "Web and mobile", technologies: ["Next.js", "TypeScript", "React Native", "Redux Toolkit", "Dexie", "Jest", "Cypress"], overview: ["Plural Health brings together electronic health records, pharmacy, insurance, laboratory, billing, inventory, and administrative workflows. I worked on frontend delivery across this product suite, where different clinical and operations roles needed clear interfaces for day-to-day work.", "The work involved turning dense requirements and API data into reusable screens, forms, tables, reports, and role-based dashboards that teams could maintain across multiple products."], contributions: ["Built shared dashboards, data tables, reports, and multi-role clinical forms.", "Engineered offline-first pharmacy flows with IndexedDB, sync retries, and conflict handling for unreliable connections.", "Supported delivery with Jest, React Testing Library, Cypress, and code review."], outcome: "The result was a more consistent frontend foundation for complex healthcare operations, including pharmacy workflows designed to keep working through connectivity interruptions.", links: [{ label: "Visit Plural Health", href: "https://plural.health/" }, { label: "Explore NeoPharmacy", href: "https://neopharm.plural.health/signup" }] },
  { slug: "betpikr", title: "Customer and operations interfaces for Betpikr", focus: "Real-time product interfaces · Operations", description: "Frontend case study on responsive customer journeys and back-office tools for Betpikr, built with React and TypeScript.", role: "Frontend Engineer", platform: "Customer web app and back office", technologies: ["React", "TypeScript", "REST APIs", "Responsive UI", "Real-time data"], overview: ["Betpikr combines a customer-facing betting experience with back-office tools for operators. Those surfaces serve different needs, but both depend on clear feedback as data changes and users move through important tasks.", "I worked on responsive journeys and operational interfaces, shaping shared patterns for live data, administration, and reporting."], contributions: ["Built responsive customer journeys and operational tools from reusable interface patterns.", "Designed loading, validation, and error states for high-intent flows.", "Worked with product, design, backend, and QA to resolve production issues."], outcome: "The work gave customers and operators clearer, more consistent ways to use the product across different screen sizes and workflows.", links: [{ label: "View Betpikr", href: "https://dev-frontend.betpikr.app/en" }] },
  { slug: "myneohealth-visilite", title: "Mobile healthcare and inventory workflows", focus: "React Native · Healthcare · Supply chain", description: "A mobile product case study covering patient access, clinical workflows, and barcode-led inventory operations for myNeoHealth and VisiLite.", role: "React Native Engineer", platform: "iOS and Android", technologies: ["React Native", "Expo", "TypeScript", "REST APIs", "EAS"], overview: ["myNeoHealth and VisiLite support different parts of healthcare work on mobile: patient access to records and visits, clinical and administrative tasks, and inventory operations for supply chains.", "I contributed to mobile workflows that needed to make important information easy to find and operational tasks practical on the move."], contributions: ["Contributed to patient access for records, results, prescriptions, and visits.", "Shipped clinical and administrative workflows for hospital professionals.", "Built inventory flows for shipments, expiry monitoring, and QR or barcode scanning."], outcome: "The mobile work brought patient, clinical, and inventory tasks into focused flows designed for phone and tablet use.", links: [{ label: "NeoEHR on the App Store", href: "https://apps.apple.com/ng/app/neoehr/id6473736118" }, { label: "myNeoHealth on Google Play", href: "https://play.google.com/store/apps/details?id=com.plateaumed.myneo" }, { label: "VisiLite on the App Store", href: "https://apps.apple.com/gb/app/visilite/id6465992591" }] }
];
export function getCaseStudy(slug: string) { return caseStudies.find((study) => study.slug === slug); }
